materials = {
    '6082':
        {'name': '6082-T6 aluminium',
         'type': 'metal',
         'yield_stress': 260E6,
         'shear_stress': 0,
         'bearing_stress': 0,
         'density': 2701,
         'thermal_expansion_coeff': 23.1,
         'youngs_modulus': 71E9,
         'shear_modulus': 26E9,
         'poisson_ratio': 0.33},
    'SS316LW':
        {'name': '316 L / 304',
         'type': 'metal',
         'yield_stress': 1240E6, 
         'shear_stress': 0,
         'bearing_stress': 0,
         'density': 8000,
         'thermal_expansion_coeff': 16.0,
         'youngs_modulus': 193E9,
         'shear_modulus': 77E9,
         'poisson_ratio': 0.25},
    '2219':
        {'name': '2219-T8',
         'type': 'metal',
         'yield_stress': 330E6, 
         'shear_stress': 0,
         'bearing_stress': 0,
         'density': 2840,
         'thermal_expansion_coeff': 22.0,
         'youngs_modulus': 72E9,
         'shear_modulus': 27E9,
         'poisson_ratio': 0.33},
    '2195':
        {'name': '2195-T8',
         'type': 'metal',
         'yield_stress': 590E6, 
         'shear_stress': 350E6,
         'bearing_stress': 0,
         'density': 3000,
         'thermal_expansion_coeff': 22.0,
         'youngs_modulus': 69E9,
         'shear_modulus': 26E9,
         'poisson_ratio': 0.33}

}